import { DEFAULT_PROJECT, type PageInfo } from '../wiki.js';
import * as fs from 'fs';
import * as path from 'path';

// HTML-encode JSON for safe embedding in HTML attributes
export function encodeJsonForAttr(data: unknown): string {
  return JSON.stringify(data)
    .replace(/&/g, '&amp;')
    .replace(/'/g, '&#39;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// Read bundle path from manifest (generated by build script)
function getBundlePath(): string {
  try {
    const manifestPath = path.join(process.cwd(), 'public/js/manifest.json');
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
    return manifest.bundle;
  } catch {
    // Fallback for development or if manifest doesn't exist
    return '/js/bundle.js';
  }
}

export interface LayoutOptions {
  title: string;
  content: string;
  pages?: PageInfo[];
  currentSlug?: string;
  project?: string;
  projects?: string[];
}

export function layout(options: LayoutOptions): string;
export function layout(title: string, content: string): string;
export function layout(
  titleOrOptions: string | LayoutOptions,
  contentArg?: string
): string {
  // Support both old signature and new options object
  const options: LayoutOptions =
    typeof titleOrOptions === 'string'
      ? { title: titleOrOptions, content: contentArg! }
      : titleOrOptions;

  const { title, content, pages = [], currentSlug = '', project = DEFAULT_PROJECT, projects = [DEFAULT_PROJECT] } = options;
  const pagesJson = encodeJsonForAttr(pages);
  const projectsJson = encodeJsonForAttr(projects);
  const bundlePath = getBundlePath();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - delve</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/style.css">
</head>
<body>
  <aside class="sidebar" id="sidebar" data-pages='${pagesJson}' data-current-slug="${currentSlug}" data-project="${project}" data-projects='${projectsJson}'>
    <div class="sidebar-header">
      <a href="/${project}" class="logo">wikai</a>
      <button class="sidebar-toggle" id="sidebar-toggle" aria-label="Toggle sidebar">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path d="M10 12L6 8L10 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
    </div>

    <div class="project-selector" id="project-selector">
      <button class="project-current" id="project-current" aria-label="Switch project">
        <span class="project-icon">📁</span>
        <span class="project-name" id="project-name">${project}</span>
        <svg class="project-chevron" width="12" height="12" viewBox="0 0 12 12" fill="none">
          <path d="M3 4.5L6 7.5L9 4.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
      <div class="project-dropdown" id="project-dropdown">
        <div class="project-list" id="project-list"></div>
        <div class="project-create" id="project-create">
          <button class="project-create-btn" id="project-create-btn">
            <span class="create-icon">+</span>
            <span>New Project</span>
          </button>
          <div class="project-create-form" id="project-create-form" style="display: none;">
            <input type="text" id="project-create-input" placeholder="Project name..." autocomplete="off" />
            <div class="project-create-actions">
              <button type="button" id="project-create-cancel" class="btn-cancel">Cancel</button>
              <button type="button" id="project-create-submit" class="btn-submit">Create</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="sidebar-search">
      <input type="text" placeholder="Search pages..." id="search-input" autocomplete="off" />
      <kbd class="shortcut-hint" data-mac="⌘K" data-other="Ctrl+K"></kbd>
    </div>

    <div class="sidebar-controls">
      <button data-sort="recent" class="sort-btn active">Recent</button>
      <button data-sort="alpha" class="sort-btn">A-Z</button>
    </div>

    <nav class="sidebar-nav">
      <section class="nav-section" id="favorites-section" style="display: none;">
        <h3>Favorites</h3>
        <ul class="page-list" id="favorites-list"></ul>
      </section>

      <section class="nav-section">
        <h3>Pages</h3>
        <ul class="page-list" id="pages-list"></ul>
      </section>
    </nav>

    <div class="sidebar-footer">
      <a href="/${project}" class="new-page-btn" id="new-page-btn">
        <span class="new-page-icon">+</span>
        <span>New Page</span>
        <kbd class="shortcut-hint" data-mac="⌘P" data-other="Ctrl+P"></kbd>
      </a>
      <a href="/_settings" class="settings-link" title="Settings">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
          <path d="M6.5 1.5L6.9 3.1C6.3 3.3 5.8 3.6 5.3 4L3.8 3.3L2.3 5.7L3.5 6.8C3.4 7.3 3.4 7.7 3.5 8.2L2.3 9.3L3.8 11.7L5.3 11C5.8 11.4 6.3 11.7 6.9 11.9L6.5 13.5H9.5L9.1 11.9C9.7 11.7 10.2 11.4 10.7 11L12.2 11.7L13.7 9.3L12.5 8.2C12.6 7.7 12.6 7.3 12.5 6.8L13.7 5.7L12.2 3.3L10.7 4C10.2 3.6 9.7 3.3 9.1 3.1L9.5 1.5H6.5Z" stroke="currentColor" stroke-width="1.2" stroke-linejoin="round"/>
          <circle cx="8" cy="7.5" r="2" stroke="currentColor" stroke-width="1.2"/>
        </svg>
      </a>
    </div>
  </aside>

  <button class="sidebar-expand-btn" id="sidebar-expand" aria-label="Open sidebar">
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
      <path d="M3 5H17M3 10H17M3 15H17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
    </svg>
  </button>

  <div class="main-wrapper">
    <main>
      ${content}
    </main>
  </div>

  <script type="module" src="${bundlePath}"></script>
</body>
</html>`;
}
